name = "wayland_protocols_ada"
description = "Ada 2012 bindings for various Wayland protocols"
version = "0.1.0"
website = "https://github.com/onox/wayland-ada"
licenses = "Apache-2.0"
tags = ["wayland", "protocols"]

authors = ["onox"]
maintainers = ["onox <denkpadje@gmail.com>"]
maintainers-logins = ["onox"]

[available.'case(os)']
linux = true
'...' = false

[[actions]]
type = "pre-build"
command = ["git", "submodule", "update", "--init"]

[[actions]]
type = "pre-build"
command = ["wayland_ada_scanner", "wayland-protocols/stable/xdg-shell/xdg-shell.xml", "src/protocols"]

[[actions]]
type = "pre-build"
command = ["wayland_ada_scanner", "wayland-protocols/stable/presentation-time/presentation-time.xml", "src/protocols"]

[[actions]]
type = "pre-build"
command = ["wayland_ada_scanner", "wayland-protocols/stable/viewporter/viewporter.xml", "src/protocols"]

[[actions]]
type = "pre-build"
command = ["wayland_ada_scanner", "wayland-protocols/unstable/idle-inhibit/idle-inhibit-unstable-v1.xml", "src/protocols"]

[[actions]]
type = "pre-build"
command = ["wayland_ada_scanner", "wayland-protocols/unstable/xdg-decoration/xdg-decoration-unstable-v1.xml", "src/protocols"]

[[actions]]
type = "pre-build"
command = ["wayland_ada_scanner", "wayland-protocols/unstable/pointer-constraints/pointer-constraints-unstable-v1.xml", "src/protocols"]

[[actions]]
type = "pre-build"
command = ["wayland_ada_scanner", "wayland-protocols/unstable/pointer-gestures/pointer-gestures-unstable-v1.xml", "src/protocols"]

[[actions]]
type = "pre-build"
command = ["wayland_ada_scanner", "wayland-protocols/unstable/relative-pointer/relative-pointer-unstable-v1.xml", "src/protocols"]

[[depends-on]]
wayland_ada_scanner = "^0.1.0"
wayland_client_ada = "^0.1.0"
