name = "wayland_cursor_ada"
description = "Ada 2012 bindings for libwayland-cursor"
version = "0.1.0"
website = "https://github.com/onox/wayland-ada"
licenses = "Apache-2.0"
tags = ["wayland"]

authors = ["onox"]
maintainers = ["onox <denkpadje@gmail.com>"]
maintainers-logins = ["onox"]

[available.'case(os)']
linux = true
'...' = false

[[depends-on]]
wayland_client_ada = "^0.1.0"
libwayland = "^1.16"
