name = "wayland_cursor_ada"
description = "Ada 2012 bindings for libwayland-cursor"
version = "1.0.0"
website = "https://github.com/onox/wayland-ada"
licenses = "Apache-2.0"
tags = ["wayland"]

authors = ["onox"]
maintainers = ["onox <denkpadje@gmail.com>"]
maintainers-logins = ["onox"]

[configuration]
disabled = true

[available.'case(os)']
linux = true
'...' = false

[[depends-on]]
libwayland = "^1.18"
wayland_client_ada = "^1.0.0"

[[pins]]
wayland_client_ada = { path = "../wayland_client_ada" }
