name = "wayland_egl_ada"
description = "Ada 2012 bindings for libwayland-egl"
version = "1.0.0"
website = "https://github.com/onox/wayland-ada"
licenses = "Apache-2.0"
tags = ["wayland", "egl"]

authors = ["onox"]
maintainers = ["onox <denkpadje@gmail.com>"]
maintainers-logins = ["onox"]

[available.'case(os)']
linux = true
'...' = false

[[depends-on]]
libwayland = "^1.16"
wayland_client_ada = "^1.0.0"
