name = "wayland_client_ada"
description = "Ada 2012 bindings for libwayland-client and the Wayland protocol"
version = "1.0.0"
website = "https://github.com/onox/wayland-ada"
licenses = "Apache-2.0"
tags = ["wayland", "client"]

authors = ["onox"]
maintainers = ["onox <denkpadje@gmail.com>"]
maintainers-logins = ["onox"]

[configuration]
disabled = true

[available.'case(os)']
linux = true
'...' = false

[[actions]]
type = "pre-build"
command = ["mkdir", "-p", "src/protocols"]

[[actions]]
type = "pre-build"
command = ["wayland_ada_scanner", "/usr/share/wayland/wayland.xml", "src/protocols"]

[[depends-on]]
wayland_ada_scanner = "^1.0.0"
libwayland = "^1.18"

[[pins]]
wayland_ada_scanner = { path = "../wayland_ada_scanner" }
